### ISSUE TITLE
Nuget Package Install Can't Find package Chaos.NaCl

### ISSUE THREAD

**Issue by ace26** [elucidsoft/dotnetcore-stellar-sdk#3]
I have tried for 2 days in futility to install the dotnetcore-stellar-sdk package and it keeps failing to successfully restore with the following error message:

"Unable to find package Chaos.NaCl. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org"

Kindly check it out.

**Comment by elucidsoft** [comment]
Interesting, that reference should be included in the project internally. I
will take a look and see why the nuget package is treating it as an
external dependency.

**Comment by elucidsoft** [comment]
Ok I found the problem, will be uploading a new nuget package shortly. I am also uploading a new version of Chaos.Nacl to Nuget for core that way all dependencies are on nuget, so I'll be separating that out and creating its own repo.

**Comment by ace26** [comment]
That's great to hear. Looking forward to this update cause I am currently using in on a project.

**Comment by elucidsoft** [comment]
https://www.nuget.org/packages/stellar-dotnetcore-sdk/1.0.3

Should resolve all of your issues, please let me know!

**Comment by ace26** [comment]
Package installs and restores just fine now.
Thanks.

**Comment by elucidsoft** [comment]
Good to hear!
